name: compile and upload release

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: fwal/setup-swift@v1

      - uses: actions/checkout@

      - name: Build
        run: swift build -c release

      - name: upload release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .build/release/EvenOddSwift